### ISSUE TITLE
Kernel crash due to file with the same name of a stdlib Python module present in opened project 

### ISSUE THREAD

**Issue by akulkanojia2414** [spyder-ide/spyder-kernels#116]
Kernel is crashing when opening a project which has same files as stdlib.

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/console/start.py", line 279, in main
import_spydercustomize()
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/customize/spydercustomize.py", line 19, in 
import pdb
File "/usr/lib/python3.6/pdb.py", line 79, in 
import signal
File "/home/akul/Documents/backtrader/signal.py", line 24, in 
import backtrader as bt
ModuleNotFoundError: No module named 'backtrader'
Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/apport_python_hook.py", line 63, in apport_excepthook
from apport.fileutils import likely_packaged, get_recent_crashes
File "/usr/lib/python3/dist‑packages/apport/__init__.py", line 5, in 
from apport.report import Report
File "/usr/lib/python3/dist‑packages/apport/report.py", line 12, in 
import subprocess, tempfile, os.path, re, pwd, grp, os, time
File "/usr/lib/python3.6/subprocess.py", line 50, in 
import signal
File "/home/akul/Documents/backtrader/signal.py", line 24, in 
import backtrader as bt
ModuleNotFoundError: No module named 'backtrader'

Original exception was:
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/console/start.py", line 279, in main
import_spydercustomize()
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/usr/local/lib/python3.6/dist‑packages/spyder_kernels/customize/spydercustomize.py", line 19, in 
import pdb
File "/usr/lib/python3.6/pdb.py", line 79, in 
import signal
File "/home/akul/Documents/RandomProject/signal.py", line 24, in 
*** Error while importing this file ***

**Comment by ccordoba12** [comment]
> /home/akul/Documents/backtrader/signal.py

Please rename or remove this file to fix your problem.
