### ISSUE TITLE
AttributeError when running any script in spyder

### ISSUE THREAD

**Issue by juler69** [spyder-ide/spyder-kernels#165]
Python 3.6.4 on MacOS 10.14.6 installed using pip
spyder 3.3.6
spyder-kernels 0.5.2
wurlitzer 1.0.3

`
Error in callback <function sys_pipes_forever at 0x129830510> (for pre_execute):
Traceback (most recent call last):

  File "/Users/p719952/Library/Python/3.6/lib/python/site-packages/wurlitzer.py", line 331, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)

  File "/Users/p719952/Library/Python/3.6/lib/python/site-packages/wurlitzer.py", line 298, in pipes
    with w:

  File "/Users/p719952/Library/Python/3.6/lib/python/site-packages/wurlitzer.py", line 151, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/Users/p719952/Library/Python/3.6/lib/python/site-packages/wurlitzer.py", line 100, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'
`

**Comment by juler69** [comment]
I worked out that if I launch spyder as an app instead of via terminal, this issue disappears.  Feel free to close this issue.

The instructions to create the app I found in this link (below the accepted answer at the time of posting this) [https://stackoverflow.com/questions/20723977/ways-to-invoke-python-and-spyder-on-osx/30033903#30033903](url)
