### ISSUE TITLE
zmq.error.ZMQError: Address in use (after reboot)

### ISSUE THREAD

**Issue by hershkoy** [spyder-ide/spyder-kernels#221]
I am running a virtualenv on windows 10 
python 3.7.4
anaconda 1.9.2

I am running the command:
python -m spyder_kernels.console

and I am getting the output:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "E:\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\lib\site-packages\ipykernel\heartbeat.py", line 91, in run
    self._bind_socket()
  File "E:\Anaconda3\lib\site-packages\ipykernel\heartbeat.py", line 74, in _bind_socket
    self._try_bind_socket()
  File "E:\Anaconda3\lib\site-packages\ipykernel\heartbeat.py", line 61, in _try_bind_socket
    return self.socket.bind('%s://%s' % (self.transport, self.ip) + c + str(self.port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
To connect another client to this kernel, use:

    --existing kernel-8296.json
```

I tried rebooting the computer and it is still happening. 
What can I do to get rid of this? It was working before,

**Comment by ccordoba12** [comment]
It looks like a problem with your firewall and/or antivirus. Please deactivate them and try again.

**Comment by hershkoy** [comment]
In the meanwhile I completely reinstalled everything (anaconda & python). It was about time to do it anyway. It works for now, so maybe next time it will happen.
Thanks

**Comment by danhamill** [comment]
I have this error when I try and restart the kernel in spyder.  Does that still sound like a firewall issue?

**Comment by ccordoba12** [comment]
@danhamill, your problem is a duplicate of issue spyder-ide/spyder#14739. We don't know why it happens.
