### ISSUE TITLE
Spyder - Anaconda

### ISSUE THREAD

**Issue by Programmfailer** [spyder-ide/spyder-kernels#331]
I can't open Spyder via Anaconda, if i want to start spyder, the loading bar will apear but after that nothing happen. Also if i want to update it to a newer version like 5.0.5, it will load until infinity.

If i want to open spyder via the terminal, this will appear:

(base) C:\Users\fuzhan>spyder
Traceback (most recent call last):
  File "C:\Users\fuzhan\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\fuzhan\anaconda3\lib\site-packages\spyder\app\start.py", line 97, in main
    from spyder.config.manager import CONF
  File "C:\Users\fuzhan\anaconda3\lib\site-packages\spyder\config\manager.py", line 351, in <module>
    CONF = ConfigurationManager()
  File "C:\Users\fuzhan\anaconda3\lib\site-packages\spyder\config\manager.py", line 64, in __init__
    self._user_config = MultiUserConfig(
  File "C:\Users\fuzhan\anaconda3\lib\site-packages\spyder\config\user.py", line 782, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "C:\Users\fuzhan\anaconda3\lib\site-packages\spyder\config\user.py", line 212, in __init__
    self._load_from_ini(previous_fpath)
  File "C:\Users\fuzhan\anaconda3\lib\site-packages\spyder\config\user.py", line 333, in _load_from_ini
    self.read(fpath, encoding='utf-8')
  File "C:\Users\fuzhan\anaconda3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\fuzhan\anaconda3\lib\configparser.py", line 1067, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from 'C:\\Users\\fuzhan\\.spyder-py3\\config\\transient.ini' [line 117]: section 'find_in_files' already exists

I have already deleted spyder, as well as anaconda and installed it new, but nothing changed.

Ps. i hope i posted this issue in the right category, i am new in GitHub.

**Comment by ccordoba12** [comment]
Hey @Programmfailer, thanks for reporting. I saw that you opened the same issue in the Spyder repository (spyder-ide/spyder#16747) so I'm going to close this one in favor of that.

I'll let you know what to do about your problem there.
