### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder-kernels#345]
There is two issues with the current approach:
 1- the comprehension detection breaks lookup for builtins in certain cases
 2- closures can not be created in the console

See below:
```
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.29.0 -- An enhanced Interactive Python.

In [1]: %debug print()
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(1)<module>()


IPdb [1]: def fun_a(): return [i for i in range(1)]

IPdb [2]: fun_a()
*** NameError: name 'range' is not defined

IPdb [3]: s
--Call--
> c:\programdata\anaconda3\lib\site-packages\ipykernel\iostream.py(500)write()
    498                 parent=self.parent_header, ident=self.topic)
    499 
--> 500     def write(self, string: str) -> int:
    501         """Write to current stream after encoding if necessary
    502 


IPdb [4]: a = 1
Warning: The exclamation mark option is enabled. Please use '!' as a prefix for Pdb commands.

IPdb [5]: def fun_a(): print(a)

IPdb [6]: fun_a()
*** NameError: name 'a' is not defined

IPdb [7]: 
```

**Comment by impact27** [comment]
Second issue can be reproduced in regular python:
```
>>> exec('a = 1\ndef fun_a(): \n    print(a)\nfun_a()\n', {}, {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 3, in fun_a
NameError: name 'a' is not defined
>>> exec('a = 1\ndef fun_a(): \n    print(a)\nfun_a()\n', {})
1
>>>
```
