### ISSUE TITLE
NameError: name 'modpath' is not defined

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder-kernels#85]
Commit 31694ab74d9c5494a2c6054d2aaeee05cfc9ec15 introduced a bug when running a file a second time.

I'm using the latest `spyder-kernels` on master with the latest `spyder` also on master.

Windows 10, Python 3.7.1 64-bit

```python
Traceback (most recent call last):

  File "<ipython-input-3-ec616f24c2fa>", line 1, in <module>
    runfile('C:/Users/User/OneDrive/INRS/2017 - Projet INRS PACC/Analyses Baro/calcul_fft.py', wdir='C:/Users/User/OneDrive/INRS/2017 - Projet INRS PACC/Analyses Baro')

  File "C:\Users\User\spyder-kernels\spyder_kernels\customize\spydercustomize.py", line 732, in runfile
    run_umr()

  File "C:\Users\User\spyder-kernels\spyder_kernels\customize\spydercustomize.py", line 716, in run_umr
    __umr__.run(verbose=verbose)

  File "C:\Users\User\spyder-kernels\spyder_kernels\customize\spydercustomize.py", line 627, in run
    if not self.is_module_blacklisted(modname, modpath):

NameError: name 'modpath' is not defined
```

**Comment by ccordoba12** [comment]
Thanks @jnsebgosselin! I'll fix it right away.

**Comment by zahra74** [comment]
would you please describe how to solve this problem  again
i do not get it

**Comment by ccordoba12** [comment]
You need to update Spyder to its 3.3.6 version to fix it.
