### ISSUE TITLE
An error ocurred while starting the kernel on Windows

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder-kernels#89]
### What steps reproduce the problem?

1. Create a fresh new Python 3.6.8 environment with conda
2. `conda install spyder-kernels==1.0.1`
3. Try starting an IPython console using the python interpreter from the new environment in Spyder

Note that `conda install python==3.6.7` fixes the issue. I'm running Spyder with latest master and `spyder-kernels==1.0.1` installed with `conda` from `defaults` on Windows10. 

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
File "C:\Anaconda3\envs\pygtide‑env\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Anaconda3\envs\pygtide‑env\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\User\spyder‑kernels\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\User\spyder‑kernels\spyder_kernels\console\start.py", line 289, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\ipykernel\__init__.py", line 2, in
from .connect import *
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\ipykernel\connect.py", line 18, in
import jupyter_client
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\jupyter_client\connect.py", line 23, in 
import zmq
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\zmq\backend\select.py", line 27, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Anaconda3\envs\pygtide‑env\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by ccordoba12** [comment]
I think this was introduced by the latest changes to the Python packages in Anaconda, aimed at removing `C:\Windows\System32` from DLL search path.

@CAM-Gerlach, could you help us to confirm if that's the case or not? Thanks!

**Comment by CAM-Gerlach** [comment]
I could not reproduce this with a clean (just created yesterday, with only the packages in our requirements files) Spyder 4 env with the latest ``master`` (at ``8d66f28b5``) and a freshly created test environment with only Spyder-Kernels 1.0.1 installed along with Python 3.6.8 on my Win 8.1 x64 system. I switched my Python interpreter path to the test environment and kernels started just fine and ran basic commands (and I verified they were under Python 3.6.8).

This should be able to be reproduced exactly with the following commands, with the cwd in the ``spyder`` repo:

```
conda create -n test-env python =3.6.8
conda activate test-env
conda install spyder-kernels=1.0.1
conda create -n spyder-env python=3.7
conda activate spyder-env
conda install -c spyder-ide --from-file requirements/conda.txt
conda install -c spyder-ide --from-file requirements/tests.txt
python bootstrap.py
```

Conda list for Spyder env:

<details>

```
(spyder-4) C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder>conda list
# packages in environment at C:\Miniconda3\envs\spyder-4:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
asn1crypto                0.24.0                   py37_0
astroid                   2.1.0                    py37_0
atomicwrites              1.3.0                      py_0
attrs                     18.2.0           py37h28b3542_0
autopep8                  1.4.3                    py37_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
ca-certificates           2019.1.23                     0
certifi                   2018.11.29               py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
cloudpickle               0.7.0                      py_0
colorama                  0.4.1                    py37_0
coverage                  4.5.2            py37he774522_0
cryptography              2.5              py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
cython                    0.29.4           py37ha925a31_0
decorator                 4.3.2                    py37_0
defusedxml                0.5.0                    py37_1
docutils                  0.14                     py37_0
entrypoints               0.3                      py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
flaky                     3.5.3                    py37_0
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imagesize                 1.1.0                    py37_0
intel-openmp              2019.1                      144
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.2.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.4                    py37_0
jedi                      0.13.2                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter_client            5.2.4                    py37_0
jupyter_core              4.4.0                    py37_0
keyring                   17.1.1                   py37_0
kiwisolver                1.0.1            py37h6538335_0
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libpng                    1.6.36               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.10               hb898794_2
markupsafe                1.1.0            py37he774522_0
matplotlib                3.0.2            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37he774522_0
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
mock                      2.0.0                    py37_0
more-itertools            5.0.0                    py37_0
mpmath                    1.1.0                    py37_0
nbconvert                 5.4.0                    py37_1
nbformat                  4.4.0                    py37_0
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
numpydoc                  0.8.0                    py37_0
olefile                   0.46                     py37_0
openssl                   1.1.1a               he774522_0
packaging                 19.0                     py37_0
pandas                    0.24.1           py37ha925a31_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py37_1
parso                     0.3.2                    py37_0
pbr                       5.1.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.4.1            py37hdc69c19_0
pip                       19.0.1                   py37_0
pluggy                    0.8.1                    py37_0
prompt_toolkit            2.0.8                      py_0
psutil                    5.5.0            py37he774522_0
py                        1.7.0                    py37_0
pycodestyle               2.5.0                    py37_0
pycparser                 2.19                     py37_0
pydocstyle                3.0.0                    py37_0
pyflakes                  2.1.0                    py37_0
pygments                  2.3.1                    py37_0
pylint                    2.2.2                    py37_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.1                    py37_0
pyqt                      5.9.2            py37h6538335_2
pysocks                   1.6.8                    py37_0
pytest                    4.0.2                    py37_0
pytest-cov                2.6.1                    py37_0
pytest-mock               1.10.0                   py37_0
pytest-qt                 3.2.1                      py_0    spyder-ide
python                    3.7.2                h8c8aaf0_2
python-dateutil           2.7.5                    py37_0
python-jsonrpc-server     0.1.2                      py_0    spyder-ide
python-language-server    0.21.5                py37_1000    spyder-ide
pytz                      2018.9                   py37_0
pywin32                   223              py37hfa6e2cd_1
pyzmq                     17.1.2           py37ha925a31_2
qdarkstyle                2.6.5                      py_0    spyder-ide
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.6                      py_0
qtconsole                 4.4.3                    py37_0
qtpy                      1.6.0                      py_0
requests                  2.21.0                   py37_0
rope                      0.11.0                   py37_0
scipy                     1.2.0            py37h29ff71c_0
setuptools                40.7.3                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snowballstemmer           1.2.1                    py37_0
sphinx                    1.8.4                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder-kernels            1.2.0                    py37_0    spyder-ide
sqlite                    3.26.0               he774522_0
sympy                     1.3                      py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
tornado                   5.1.1            py37hfa6e2cd_0
traitlets                 4.3.2                    py37_0
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.32.3                   py37_0
win_inet_pton             1.0.1                    py37_1
wincertstore              0.2                      py37_0
wrapt                     1.11.1           py37he774522_0
xz                        5.2.4                h2fa13f4_4
yapf                      0.25.0                   py37_0
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

</details>

Conda list for interpreter environment:

<details>

```
(test-env) C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder>conda list
# packages in environment at C:\Miniconda3\envs\test-env:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                    py36_0
certifi                   2018.11.29               py36_0
cloudpickle               0.7.0                      py_0
colorama                  0.4.1                    py36_0
decorator                 4.3.2                    py36_0
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.2.0            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
jedi                      0.13.2                   py36_0
jupyter_client            5.2.4                    py36_0
jupyter_core              4.4.0                    py36_0
libsodium                 1.0.16               h9d3ae62_0
parso                     0.3.2                    py36_0
pickleshare               0.7.5                    py36_0
pip                       19.0.1                   py36_0
prompt_toolkit            2.0.8                      py_0
pygments                  2.3.1                    py36_0
python                    3.6.8                h9f7ef89_1
python-dateutil           2.7.5                    py36_0
pyzmq                     17.1.2           py36ha925a31_2
setuptools                40.7.3                   py36_0
six                       1.12.0                   py36_0
spyder-kernels            1.0.1                    py36_0
sqlite                    3.26.0               he774522_0
tornado                   5.1.1            py36hfa6e2cd_0
traitlets                 4.3.2            py36h096827d_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7            py36h3d5aa90_0
wheel                     0.32.3                   py36_0
wincertstore              0.2              py36h7fe50ca_0
zeromq                    4.3.1                h33f27b4_3
```

</details>

**Comment by svdHero** [comment]
I have the same problem, but I am using Python 3.7 and in my case it only happens, once I import any module.

I followed [this section](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach) in the Spider IDE wiki, in order to work with different environments inside Spyder.

However, when I change the path in `Tools -> Preferences -> Python Interpreter -> Use the following interpreter` to my conda environment called "my-test-env" and run a script `test.py`, it fails with the following error message:
```
runfile('C:/Users/svdhero/Desktop/test/test.py', wdir='C:/Users/svdhero/Desktop/test')
Traceback (most recent call last):

  File "<ipython-input-1-e16cf07cf7fc>", line 1, in <module>
    runfile('C:/Users/svdhero/Desktop/test/test.py', wdir='C:/Users/svdhero/Desktop/test')

  File "C:\Users\svdhero\AppData\Local\Continuum\anaconda3\envs\my-test-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 826, in runfile
    execfile(filename, namespace)

  File "C:\Users\svdhero\AppData\Local\Continuum\anaconda3\envs\my-test-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/svdhero/Desktop/test/test.py", line 1, in <module>
    import numpy as np

  File "C:\Users\svdhero\AppData\Local\Continuum\anaconda3\envs\my-test-env\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init

  File "C:\Users\svdhero\AppData\Local\Continuum\anaconda3\envs\my-test-env\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit

ImportError: DLL load failed: The specified module could not be found.
```

In order to reproduce this error, execute the following commands in the Anaconda Prompt:
```
conda create -n spyder4-env python=3.7
conda activate spyder4-env
conda install -c spyder-ide spyder=4.0.0b4
deactivate

conda create -n my-test-env python=3.7
conda activate my-test-env
conda install numpy spyder-kernels=1.4.0

python -c "import numpy as np; print(f'Pi = {np.pi}')"
```
The number Pi should be printed successfully inside the conda environment `my-test-env`.

Then:

1. Start Spyder from the `spyder4-env`.
1. Create a script `test.py` with the content `import numpy as np; print(f'Pi = {np.pi}')`
1. Change the Python interpreter in the Spyder preferences.
1. Run the script `test.py` inside Spyder in order to get the DLL error above.

I am using Anaconda3 2019.07 (Python 3.7.3 64-Bit) on Windows 8.1.

**Comment by ccordoba12** [comment]
@svdHero, what's your Windows version?

**Comment by svdHero** [comment]
Like I wrote above: Windows 8.1 x64, the same version as @CAM-Gerlach.

**Comment by ccordoba12** [comment]
@dalthviz, are you able to reproduce this problem?

**Comment by ccordoba12** [comment]
@svdHero, thanks for the reproducible example. I was able to reproduce the problem and I know how to fix it now.

We'll try to do it for Spyder 4.

**Comment by svdHero** [comment]
Thanks @ccordoba12  for all your work on Spyder. Looking forward to the Spyder 4 release.

**Comment by water-e** [comment]
@ccordoba12 I'm still having similar trouble in 4.0.0 rc2 with python 3.7 and spyder-kernels-1.4.0. Something as simple as "import matplotlib.pyplot as plt" fails when I install spyder in base environment and point to matplotlib in a working environment as my interpreter. Is this advertised as ready for this use case?

**Comment by CAM-Gerlach** [comment]
@water-e Please upgrade to the latest version of Spyder-Kernels in both your Spyder and your working environment; Spyder 4.0.0rc2 officially requires Spyder-Kernels >=1.8.0, which is the latest version (although for some reason it isn't actually tagged as a release on this repo even though its on ``spyder-ide``... @ccordoba12 ?) , while you are running a much older version. Also, please share your specific Python version (as has been already stated here, the point version of Python makes a difference to this issue) and upgrade to the latest point version in both environments. Thanks.

**Comment by water-e** [comment]
OK, I've upgraded as shown below. I still get DLL load failed when I type `import matplotlib` in spyder and no issue at an anaconda prompt. I don't know that I can do much more -- is there more to it?

base
python                    3.7.5                h8c8aaf0_0
spyder                    4.0.0rc2                 py37_0    spyder-ide
spyder-kernels            1.8.0                    py37_0    spyder-ide

python                    3.7.5                h8c8aaf0_0
spyder-kernels            1.8.0                    py37_0    spyder-ide

**Comment by CAM-Gerlach** [comment]
@water-e Please paste the exact text of the full error traceback here so it can be analyzed. Also, try setting the environment variable `CONDA_DLL_SEARCH_NOTIFICATION_ENABLE` to `1` (in Windows Advanced System Settings) and reboot your machine to enable the new Anaconda DLL loading behavior globally for your user account, and try Spyder again. If that fixes it, you likely have a conflicting DLL that some misbehaving program dumped in your System32.

**Comment by water-e** [comment]
The env var was visible in os.environ but didn't change the behavior. Thanks for all the help!

Here is the full traceback:
runfile('C:/Users/eli/.spyder-py3-dev/temp.py', wdir='C:/Users/eli/.spyder-py3-dev')
Traceback (most recent call last):

  File "C:\Users\eli\.spyder-py3-dev\temp.py", line 8, in <module>
    import matplotlib.pyplot as plt

  File "C:\Users\eli\miniconda3\envs\py37\lib\site-packages\matplotlib\__init__.py", line 205, in <module>
    _check_versions()

  File "C:\Users\eli\miniconda3\envs\py37\lib\site-packages\matplotlib\__init__.py", line 190, in _check_versions
    from . import ft2font

ImportError: DLL load failed: The specified module could not be found.

**Comment by water-e** [comment]
OK, actually the environment variable did work but it had a typo. It should be 
CONDA_DLL_SEARCH_MODIFICATION_ENABLE to 1

Thanks again!!

**Comment by CAM-Gerlach** [comment]
@water-e Ironically I copied it from @mingwandroid 's comment [here](https://github.com/ContinuumIO/anaconda-issues/issues/10628#issuecomment-466628653) to ensure I didn't mistype it myself, heh. Glad it worked!
