### ISSUE TITLE
AttributeError when trying to load wurlitzer

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-kernels#94]
This error was reported in https://github.com/spyder-ide/spyder/issues/8668. I think we need to fix it in wurlitzer itself.

```python-traceback
Traceback (most recent call last):

File "/Users/Suman/anaconda/lib/python3.6/site-packages/wurlitzer.py", line 320, in sys_pipes_forever
_mighty_wurlitzer.enter()

File "/Users/Suman/anaconda/lib/python3.6/contextlib.py", line 81, in enter
return next(self.gen)

File "/Users/Suman/anaconda/lib/python3.6/site-packages/wurlitzer.py", line 290, in pipes
with w:

File "/Users/Suman/anaconda/lib/python3.6/site-packages/wurlitzer.py", line 151, in enter
pipe = self._setup_pipe('stdout')

File "/Users/Suman/anaconda/lib/python3.6/site-packages/wurlitzer.py", line 100, in _setup_pipe
real_fd = getattr(sys, '%s' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'
```

**Comment by Keou0007** [comment]
I just installed beta2 on my mac and got this same error line for line on launching. 
Tt actually threw the exception three times in row.
I updated wurlitzer to the version in the spyder-ide conda channel and no more errors.
I'm afraid I don't have a lot more insight, but I'd be happy to test something if you have any theories.

**Comment by ccordoba12** [comment]
> I updated wurlitzer to the version in the spyder-ide conda channel and no more errors.

So is this fixed with the latest `wurlitzer` version (1.0.2)?

**Comment by Keou0007** [comment]
I haven't seen any more errors since I updated. So maybe?
None of my channels show any earlier versions anymore, so I don't think I can downgrade to test.

**Comment by ccordoba12** [comment]
Ok, let's close this for now then. Thanks for the confirmation @Keou0007!
